# Generated by Django 5.0 on 2023-12-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('clan', models.CharField(default='lowborn', max_length=200, verbose_name='Clan')),
                ('birth', models.PositiveIntegerField(verbose_name='Year of Birth')),
                ('statSTR', models.SmallIntegerField(default=5, verbose_name='Strength')),
                ('statDEX', models.SmallIntegerField(default=5, verbose_name='Dexterity')),
                ('statAGI', models.SmallIntegerField(default=5, verbose_name='Agility')),
                ('statRES', models.SmallIntegerField(default=5, verbose_name='Resilience')),
                ('percentHP', models.SmallIntegerField(default=100, verbose_name='Health')),
                ('percentST', models.SmallIntegerField(default=100, verbose_name='Stamina')),
                ('status', models.CharField(choices=[('WR', 'Working'), ('RT', 'Retired'), ('DE', 'Dead'), ('IN', 'Injured')], default='WR', max_length=2)),
            ],
        ),
    ]
